
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';


export const USER_APPLY_FORM_REQUEST = 'USER_APPLY_FORM_REQUEST'
export const USER_APPLY_FORM_SUCCESS = 'USER_APPLY_FORM_SUCCESS';
export const  USER_APPLY_FORM_FAIL = 'USER_APPLY_FORM_FAIL';